flaskproject/games/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import PasswordField, SelectField, StringField, SubmitField
from wtforms.validators import DataRequired, Length


class GameForm(FlaskForm):
    name = StringField("Title", default="Default Name", validators=[DataRequired()])

    password = PasswordField("Password", validators=[Length(min=3, max=8)])
    picture = FileField(
        "Update Profile Picture", validators=[FileAllowed(["jpg", "png"])]
    )
    submit = SubmitField("Create Game")


class EnterGameForm(FlaskForm):
    game_id = StringField(
        "Game ID:", default="Insert Number", validators=[DataRequired()]
    )

    password = PasswordField("Password")
    submit = SubmitField("Enter Game")


class WinnerForm(FlaskForm):
    group_id = SelectField(
        u"group_id", choices=[], validators=[DataRequired()], coerce=int
    )
    submit = SubmitField("Add result")

flaskproject/games/routes.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from flaskproject import bcrypt, db
from flaskproject.games.forms import EnterGameForm, GameForm, WinnerForm
from flaskproject.games.utils import calculate_elo, save_picture
from flaskproject.models import Game, User

games = Blueprint("games", __name__)


@games.route("/game/new", methods=["GET", "POST"])
@login_required
def create_game():
    form = GameForm()

    if form.validate_on_submit():

        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        game = Game(name=form.name.data, password=hashed_pw)

        if form.picture.data:
            picture_fn = save_picture(form.picture.data)
            game.image_file = picture_fn

        game.players.append(current_user)

        db.session.add(game)
        db.session.commit()

        flash("Your game has been created!", "success")

        return redirect(url_for("games.view_game", game_id=game.id))

    return render_template("create_game.html", title="Create game", form=form)


@games.route("/game/enter", methods=["GET", "POST"])
@login_required
def enter_game():
    form = EnterGameForm()
    if form.validate_on_submit():

        game = Game.query.get(form.game_id.data)
        if game is None:
            flash("Game does not exist!", "danger")
            return redirect(url_for("games.enter_game"))

        if current_user not in game.players and len(game.players) == 1:

            if bcrypt.check_password_hash(game.password, form.password.data):
                game.players.append(current_user)
                db.session.commit()
            else:
                flash("Wrong password!", "danger")
                return redirect(url_for("games.enter_game"))
        flash("Game already full", "warning")

        return redirect(url_for("games.view_game", game_id=game.id))

    return render_template(
        "join_game.html", title="Join game", form=form, legend="Create"
    )


@games.route("/game/<int:game_id>/view", methods=["GET", "POST"])
def view_game(game_id):
    """

    ToDo: add ability to keep the games going after the winner as been decided

    :param game_id:
    :return:
    """

    game = Game.query.get_or_404(game_id)

    form = WinnerForm()
    choices = [(0, "TBD")]

    players = [i for i in game.players]

    for j in range(len(players)):
        choices.append((j + 1, players[j].username))

    form.group_id.choices = choices

    if form.validate_on_submit() and form.group_id.data != -1:
        flash("Your game has been updated 1!", "success")
        p1_elo, p2_elo = calculate_elo(
            game.players[0].elo, players[1].elo, form.group_id.data
        )

        players[0].elo = p1_elo
        players[1].elo = p2_elo
        game.winner = players[form.group_id.data - 1].id

        db.session.commit()

        flash("The winner has been decided !", "success")

        return redirect(url_for("main.home"))

    return render_template(
        "game.html",
        title="View game",
        game=game,
        creator=players[0],
        form=form,
        players=players,
    )


@games.route("/game/<int:game_id>/delete", methods=["GET", "POST"])
@login_required
def delete_game(game_id):
    """
    :param game_id:
    :return:
    """

    # TODO: implement notification system to notify the users that
    # the game has been deleted
    game = Game.query.get_or_404(game_id)

    if current_user != game.players[0]:
        abort(403)

    db.session.delete(game)
    db.session.commit()
    flash("Your game has been deleted!", "success")

    return redirect(url_for("main.home"))


@games.route("/game/<int:game_id>/update/", methods=["GET", "POST"])
@login_required
def update_game(game_id):
    """

    Update game name and password

                To be implemented
    :param game_id:
    :return:
    """

    abort(404)


@games.route("/game/<int:game_id>/<int:user_id>/exit", methods=["GET", "POST"])
@login_required
def exit_game(game_id, user_id):
    """
    Exits the game. If there is only one player then the game is deleted.

    :param game_id:
    :param user_id:
    :return:
    """

    game = Game.query.get_or_404(game_id)
    players = [i for i in game.players]
    if current_user not in game.players:
        abort(405)

    else:
        if len(players) == 1:
            delete_game(game.id)
            return redirect(url_for("main.home"))

        if players[0].id == user_id:
            game.players.remove(game.players[0])
        else:
            game.players.remove(game.players[1])

    db.session.commit()
    flash("You exited the game!", "success")

    return redirect(url_for("main.home"))


@games.route("/game/match_history/<string:which>/<int:user_id>", methods=["GET"])
@login_required
def match_history(which, user_id):
    """
    See all games in which a user is in
    :return:
    """
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(id=user_id).first_or_404()
    if which == "all":
        games = user.games.order_by(Game.date_created.desc())
    elif which == "active":
        games = user.games.filter_by(winner=None).order_by(Game.date_created.desc())
    elif which == "closed":
        games = user.games.filter(Game.winner is not None).order_by(
            Game.date_created.desc()
        )

    tots = 0
    wins = 0

    game_info = {}
    for j in games:
        if j.winner:
            tots += 1
            if j.winner == user_id:
                wins += 1

    game_info["total_number"] = tots
    try:
        game_info["wins"] = wins * 100 / tots
    except ZeroDivisionError:
        game_info["wins"] = 100
    games_in = games.paginate(page=page, per_page=5)
    return render_template(
        "all_games.html",
        games=games_in,
        title=" All Games",
        user=user,
        game_info=game_info,
    )

flaskproject/main/routes.py
from flask import Blueprint, render_template, request

from flaskproject.models import User

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    users = User.query.order_by(User.elo.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", users=users)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

flaskproject/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from flaskproject import bcrypt, db
from flaskproject.models import User
from flaskproject.users.forms import (
    LoginForm,
    RegistrationForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from flaskproject.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Your account has been created. You are now able to log in", "success")

        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")

            return redirect(next_page) if next_page else redirect(url_for("main.home"))

        flash("Login unsuccessful!", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():

        if form.picture.data:
            picture_fn = save_picture(form.picture.data)
            current_user.image_file = picture_fn

        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()

        flash("Your account has been updated", "success")
        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    """
    Route in which the email is entered to request a password change
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            " An email has been sent with instructions to reset your password", "info"
        )
        return redirect(url_for("users.login"))

    return render_template("reset_request.html", title="Reset password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    """
    Route in which the password is changed if the token is valid
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    user = User.verify_reset_token(token)

    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("reset_request"))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_pw
        db.session.commit()

        flash("Your password has been updated.", "success")

        return redirect(url_for("users.login"))

    return render_template("reset_token.html", title="Reset password", form=form)

flaskproject/templates/about.html
{% extends "layout.html" %}

{% block content %}
	<h1>About</h1>
{% endblock content %}

flaskproject/templates/account.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src= "{{ image_file }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{current_user.username}}</h2>
	      <p class="text-secondary">{{current_user.email}}</p>
	    </div>
	  </div>
		<form method="POST" action ="" enctype = "multipart/form-data">
			{{form.hidden_tag()}}

			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Account info </legend>	
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors%}
						{{ form.username(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif%}

				</div>		

				<div class="form-group">
					{{form.email.label(class="form-control-label")}}
					{% if form.email.errors%}
						{{ form.email(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif%}
				</div>	

			<div class="form-group">
					{{form.picture.label()}}
					{{form.picture( class = "form-control-file")}}

					{% if form.picture.errors%}
						{% for error in form.picture.errors %}
							<span class = "text-danger">{{ error}} </span><\br>
						{% endfor %}

					{% endif %}

			</div>
			</fieldset>

			<div class="form-group">
				{{form.submit( class = "btn btn-outline-info")}}

			</div>
				

		</form>
	
	</div>

	
{% endblock content %}

flaskproject/templates/all_games.html
{% extends "layout.html" %}

{% block content %}
    <div class="btn-group">
  <button onclick="location.href='{{ url_for('games.match_history',user_id =user.id,which = 'all' )}}'"  >All</button>
  <button onclick="location.href='{{ url_for('games.match_history',user_id =user.id,which = 'active' )}}'" >Active</button>
  <button onclick="location.href='{{ url_for('games.match_history',user_id =user.id,which = 'closed' )}}'">Closed</button>
</div>
{% for game in games.items %}
		<article class="media content-section">
			<img class = "rounded-circle article-img" src=" {{ url_for('static', filename = 'game_pics/' + game.image_file)}}">
		  <div class="media-body">
		    <div class="article-metadata">
            Game title:
		    <a class="mr-2" href=" {{ url_for('games.view_game', game_id = game.id )}}">{{ game.name }}</a>

				<small class="text-muted">{{ game.date_created.strftime('%Y-%m-%d') }}</small>
                      {% if game.winner %}

            {% endif %}
		    </div>
                <h2 ><a {%  if game.winner %} {% if game.winner == game.players[0].id %} style="color:green" {% else %}style="color:darkred" {% endif %} {% endif %}

                        class="article-title" href=" {{ url_for('games.match_history', user_id = game.players[0].id, which = 'all' )}}">{{ game.players[0].username }}</a>


                    {% if game.players[1]%}
                	<b> vs </b>
              		<a {%  if game.winner %} {% if game.winner == game.players[1].id %} style="color:green" {% else %}style="color:darkred" {% endif %} {% endif %}
                            class="article-title" href=" {{ url_for('games.match_history', user_id = game.players[1].id, which = 'all' )}}">{{ game.players[1].username }}</a></h2>
                {% endif %}
		  </div>
		</article>
	{% endfor %}

	{% for page_num in games.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
		{% if page_num %}
			{% if games.page == page_num %}
				<a class = "btn btn-info mb-4" href=" {{url_for('games.match_history',page = page_num, user_id = user.id, which = 'all')}}">{{ page_num }} </a>
			{% else %}
				<a class = "btn btn-outline-info mb-4" href=" {{url_for('games.match_history',page = page_num,user_id = user.id, which = 'all')}}">{{ page_num }} </a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{%endfor%}
{% endblock content %}

{% block sidebar %}
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>General information</h3>
	          <ul class="list-group">
                  <div class="media">
			    <img class = "rounded-circle article-img" src=" {{ url_for('static', filename = 'profile_pics/' + user.image_file)}}">
                  <div class="media-body">
	                <h3 class="text-secondary">{{user.username}}</h3>
	                <small class="bot-three">Playing since: {{ user.date_created.year }} </small>
	            </div> </div>

	            <li class="list-group-item list-group-item-light"> Elo: {{ user.elo | int }}  </li>
	            <li class="list-group-item list-group-item-light"> Win rate: {{ game_info['wins'] | int }} % </li>
	          </ul>
	        </p>
	      </div>
	    </div>
{% endblock sidebar %}

flaskproject/templates/create_game.html
{% extends "layout.html" %}

{% block content %}
	<div class = "content-section">
		<form method="POST" action ="" >
			{{form.hidden_tag()}}

			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> {{ legend }} </legend>	

				<div class="form-group">
					{{form.name.label(class="form-control-label")}}
					{% if form.name.errors%}
						{{ form.name(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.name.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif%}
				</div>	

				<div class="form-group">
					{{form.password.label(class="form-control-label")}}
					{% if form.password.errors%}
						{{ form.password(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif%}
				</div>

				<div class="form-group">
					{{form.picture.label()}}
					{{form.picture( class = "form-control-file")}}

					{% if form.picture.errors%}
						{% for error in form.picture.errors %}
							<span class = "text-danger">{{ error}} </span><\br>
						{% endfor %}

					{% endif %}

			</div>
			</fieldset>

			<div class="form-group">
				{{form.submit( class = "btn btn-outline-info")}}

			</div>
			
		</form>
    </div>
{% endblock content %}

flaskproject/templates/game.html
{% extends "layout.html" %}
{% block content %}



<article class="media content-section">

	<img class="rounded-circle account-img" src= "{{ url_for('static', filename = 'game_pics/' + game.image_file) }}">
	<div class="media-body">

		<h1 class="article-title" align = center>{{ game.name }}</h1>
				<div align = center>
					<h4 class="text-muted"> Game Id: {{ game.id }}</h4>
				</div>

		<div class="article-metadata">
			<div align="center">
			<small class="text-muted">{{ game.date_created.strftime('%Y-%m-%d') }}</small>

			</div>
		</div>
			<div align = center>

				<div>
					{% if game.winner %}
                        {% if game.winner == players[0].id %}
					        <a class="mr-2" href=" {{ url_for('games.match_history', user_id = players[0].id, which = 'all' )}} ">Winner: {{players[0].username}}</a>
                        {% else %}
                            <a class="mr-2" href=" {{ url_for('games.match_history', user_id  = players[1].id, which = 'all' )}} ">Winner: {{players[1].username}}</a>

                    {% endif %}
					{% else %}
                        {% if players[1]  %}
                        <form method = 'POST' class="form-group">
                            {{ form.csrf_token }}
                            {{form.group_id}}


                                {{ form.submit( class = "btn btn-outline-info") }}
                        </form>
                        {% endif %}

					{% endif %}
				</div>

				{% if creator == current_user %}
					<div>


						<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('games.update_game', game_id=game.id) }}">Update</a>
						<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('games.exit_game', game_id=game.id, user_id = current_user.id) }}">Leave game</a>
						<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>

					</div>
				{% else %}
					{% if current_user in players %}
					<div>
						<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('games.update_game', game_id=game.id) }}">Update</a>
						<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('games.exit_game', game_id=game.id, user_id = current_user.id) }}">Leave game</a>
					</div>
					{% endif %}

				{% endif %}

		</div>
		</div>
</article>

<article class="media content-section">

	<div class="media-body">
		{% if players[1] %}
		<div class="article-metadata">
		 {% else %}
			<div>
		{% endif %}
				<h3>Player 1:</h3>
			  <div class="column left">
				<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + creator.image_file) }}">
				<a class="mr-2" href=" {{ url_for('games.match_history', user_id = creator.id, which = 'all' )}} ">{{ creator.username }}; Elo = {{ creator.elo|int}}</a>

			  </div>


			<br />
		</div>

		{% if players[1] %}
		<div class="article-metadata">
			<h3>Player 2: </h3>
			  <div class="column left">
				<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + players[1].image_file) }}">
				<a class="mr-2" href=" {{ url_for('games.match_history', user_id = players[1].id, which = 'all' )}} ">{{ players[1].username }}; Elo = {{players[1].elo|int}}</a>
			  </div>
			<br />
		</div>

		{% else %}


		{% endif %}


</article>

	  <!-- Modal -->
	  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	    <div class="modal-dialog" role="document">
	      <div class="modal-content">
	        <div class="modal-header">
	          <h5 class="modal-title" id="deleteModalLabel">Delete Game?</h5>
	          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	            <span aria-hidden="true">&times;</span>
	          </button>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	          <form action="{{ url_for('games.delete_game', game_id=game.id) }}" method="POST">
	            <input class="btn btn-danger" type="submit" value="Delete">
	          </form>
	        </div>
	      </div>
	    </div>
  </div>
{% endblock content %}

flaskproject/templates/home.html
{% extends "layout.html" %}

{% block content %}

	{% for user in users.items %}
		<article class="media content-section">
			<img class = "rounded-circle article-img" src=" {{ url_for('static', filename = 'profile_pics/' + user.image_file)}}">
		  <div class="media-body">
		    <div class="article-metadata">

				<a class="mr-2" href="{{url_for('games.match_history',user_id = user.id, which = 'all')}} ">{{ user.username }}</a>

		    </div>
              <small class="text-muted">Elo: {{ user.elo|int }}</small>

		  </div>
		</article>
	{% endfor %}

	{% for page_num in users.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
		{% if page_num %}
			{% if users.page == page_num %}
				<a class = "btn btn-info mb-4" href=" {{url_for('main.home',page = page_num)}}">{{ page_num }} </a>
			{% else %}
				<a class = "btn btn-outline-info mb-4" href=" {{url_for('main.home',page = page_num)}}">{{ page_num }} </a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{%endfor%}
{% endblock content %}

flaskproject/templates/layout.html
<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css')}}">

	{%if title%}
		<title>{{title}}</title>
	{%else%}
		<title>Default_Title</title>

	{%endif%}
	
</head>
<body>

	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Flask Blog</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
	          <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %}
					<a class="nav-item nav-link" href="{{url_for('games.create_game')}}">New Game</a>
					<a class="nav-item nav-link" href="{{url_for('games.enter_game')}}">Join Game</a>
                    <a class="nav-item nav-link" href="{{url_for('games.match_history', user_id = current_user.id, which = 'closed')}}"> Match History</a>
	        		<a class="nav-item nav-link" href="{{url_for('users.account')}}"> {{current_user.username }}</a>
	        		<a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>

	        	{% else %}
	        	
					<a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
					<a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
	          	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	
	    	{% with messages = get_flashed_messages(with_categories = True) %}
	    		{% if messages %}
	    			{% for category, message in messages %}
	    				<div class = "alert alert-{{ category }}">
	    					{{ message }}
	    				</div>
	    			{% endfor %}
	    		{%endif%}
	    	{% endwith%}
	    	{% block content %}{% endblock %}
	    
	    </div>
       {% block sidebar %}{% endblock %}

	  </div>
	</main>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 

</body>
</html>

flaskproject/templates/login.html
{% extends "layout.html" %}

{% block content %}
	<div class = "content-section">
		<form method="POST" action ="" >
			{{form.hidden_tag()}}

			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Log in </legend>	

				<div class="form-group">
					{{form.email.label(class="form-control-label")}}
					{% if form.email.errors%}
						{{ form.email(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif%}
				</div>	

				<div class="form-group">
					{{form.password.label(class="form-control-label")}}
					{% if form.password.errors%}
						{{ form.password(class="form-control form-control-lg is-invalid") }}

						<div class= "invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error}} </span>
							{% endfor %}
						</div>

					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif%}
				</div>	

				<div class = "form-check">
					{{ form.remember(class = "form-check-input")}}
					{{ form.remember.label(class = "form-check-label")}}
				</div>
				
			</fieldset>

			<div class="form-group">
				{{form.submit( class = "btn btn-outline-info")}}

			        <small class="text-muted ml-2">
			           <a href="{{ url_for('users.reset_request')}}">Forgot your Password? </a>
			        </small>

	
		
			
			    
    </div>	

		</form>
	</div>
    <div class="border-top pt-3">
        <small class="text-muted">
           Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up
           </a>
        </small>
    </div>
{% endblock content %}